# ISO 3166-1 alpha-2 codes with names. Curated list of countries with
# meaningful SME populations. Add more as needed.
COUNTRIES = [
    ("TR", "Türkiye"),
    ("DE", "Almanya"),
    ("AT", "Avusturya"),
    ("AZ", "Azerbaycan"),
    ("BE", "Belçika"),
    ("AE", "Birleşik Arap Emirlikleri"),
    ("GB", "Birleşik Krallık"),
    ("US", "Amerika Birleşik Devletleri"),
    ("BR", "Brezilya"),
    ("CN", "Çin"),
    ("DK", "Danimarka"),
    ("FI", "Finlandiya"),
    ("FR", "Fransa"),
    ("NL", "Hollanda"),
    ("HK", "Hong Kong"),
    ("IN", "Hindistan"),
    ("IE", "İrlanda"),
    ("ES", "İspanya"),
    ("SE", "İsveç"),
    ("CH", "İsviçre"),
    ("IT", "İtalya"),
    ("JP", "Japonya"),
    ("CA", "Kanada"),
    ("QA", "Katar"),
    ("KZ", "Kazakistan"),
    ("CY", "Kıbrıs"),
    ("LU", "Lüksemburg"),
    ("HU", "Macaristan"),
    ("MX", "Meksika"),
    ("EG", "Mısır"),
    ("NO", "Norveç"),
    ("UZ", "Özbekistan"),
    ("PL", "Polonya"),
    ("PT", "Portekiz"),
    ("RO", "Romanya"),
    ("RU", "Rusya"),
    ("SA", "Suudi Arabistan"),
    ("SG", "Singapur"),
    ("CZ", "Çek Cumhuriyeti"),
    ("GR", "Yunanistan"),
    ("AU", "Avustralya"),
    ("NZ", "Yeni Zelanda"),
    ("ZA", "Güney Afrika"),
]

COUNTRY_CODES = {c for c, _ in COUNTRIES}
COUNTRY_NAMES = dict(COUNTRIES)
